# Generated by Django 5.0.2 on 2025-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo', '0002_recognizedface_delete_facedetectionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedface',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
